#! /bin/sh

#### AUTOSTART ####
sxhkd &
/home/bm/.config/bspwm/mon.sh
/home/bm/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr
picom -f -b
####     -     ####

#### MONITOR ####
bspc monitor LVDS1 -d I II III IV
bspc monitor VGA1 -d  V VI VII VIII

##
####    -    ####

#### CONFIGS ####
bspc config focus_follows_pointer true
#bspc config top_padding		38
bspc config bottom_padding	5
bspc config left_padding	5
bspc config right_padding	5
bspc config border_width	0
bspc config window_gap		8
bspc config borderless_monocle	true
bspc config gapless_monocle	true
####    -    ####

#### RULES ####
bspc rule -a feh state=fullscreen
bspc rule -a vlc desktop='^1' follow=on state=fullscreen
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a burp-StartBurp desktop='^3' follow=on
bspc rule -a Wireshark desktop='^4' follow=on
bspc rule -a firefox desktop='^5' follow=on
bspc rule -a discord desktop='^6'
bspc rule -a Spotify desktop='^7' follow=on
bspc rule -a Pavucontrol desktop='^8' follow=on
bspc rule -a Thunar desktop='^8' follow=on

###
####   -   ####
